version: "3.8"
networks:
    app-network:
        driver: bridge
  
services:
    lb:
        image: haproxy:2.3
        restart: always
        ports:
            - "3005:3005"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
        deploy:
            resources:
                limits:
                    memory: 500M
        container_name: Haproxy
    rabbitmq3:
        container_name: "kroliczek"
        image: rabbitmq:3.8-management-alpine
        env_file:
            - dockerfiles/common/.common.env
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
        networks:
            - app-network
    nest-main-server:
        container_name: main-god
        image: dockerfiles/main-server/dockerfile
        hostname: main-god
        restart: on-failure:3
        env_file: 
            - dockerfiles/common/.common.env
            - dockerfiles/main-server/.env
        build:
            context: ../
            dockerfile: docker/dockerfiles/main-server/dockerfile
        ports:
            - '3000:3000'
        volumes:
            - "../server/main-server/src:/server/main-server/src"
        networks:
            - app-network
    auth-service:
        container_name: guardian-angel
        image: dockerfiles/auth-service/dockerfile
        hostname: guardian-angel
        restart: on-failure:3
        env_file: 
            - dockerfiles/auth-service/.env
            - dockerfiles/common/.common.env
        build:
            context: ../
            dockerfile: docker/dockerfiles/auth-service/dockerfile
        volumes:
            - "../server/auth-service/src:/server/auth-service/src"
        networks:
            - app-network

volumes:
    files:
    nest-main-server:
    auth-service:

