version: "3.8"
networks:
    app-network:
        driver: bridge
  
services:
    load-balancer:
        image: haproxy:2.3
        restart: always
        env_file:
            - .env
        ports:
            - "${LOAD_BALANCER_PORT}:${LOAD_BALANCER_PORT}"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
        deploy:
            resources:
                limits:
                    memory: 500M
        container_name: Haproxy-LOAD-BALANCER
    rabbitmq3:
        container_name: "kroliczek"
        image: rabbitmq:3.8-management-alpine
        env_file:
            - .env
        ports:
            # AMQP protocol port
            - '${BUNNY_CONNECTION_PORT}:${BUNNY_CONNECTION_PORT}'
            # HTTP management UI
            - '15672:15672'
        hostname: ${BUNNY_HOSTNAME}
        depends_on:
            - load-balancer
    nest-main-server:
        container_name: main-server
        image: dockerfiles/main-server/dockerfile
        hostname: "${MAIN_SERVER_HOSTNAME}"
        restart: on-failure:3
        env_file: 
            - .env
            - dockerfiles/main-server/.env
        build:
            context: ../
            dockerfile: docker/dockerfiles/main-server/dockerfile
        volumes:
            - "../server/main-server/src:/server/main-server/src"

    auth-service:
        container_name: auth-server
        image: dockerfiles/auth-service/dockerfile
        hostname: "${AUTH_SERVER_HOSTNAME}"
        restart: on-failure:3
        env_file: 
            - dockerfiles/auth-service/.env
            - .env
        build:
            context: ../
            dockerfile: docker/dockerfiles/auth-service/dockerfile
        volumes:
            - "../server/auth-service/src:/server/auth-service/src"
        depends_on:
            - rabbitmq3
volumes:
    files:
    nest-main-server:
    auth-service:

