#!/bin/bash
set -e

# echo "${POSTGRES_DATABASE_NAME}"
# set PGPASSWORD="${POSTGRES_PASSWORD}"
# psql -c "CREATE DATABASE IF NOT EXISTS ${POSTGRES_DATABASE_NAME}" -U  "${POSTGRES_USER};"
    

# sudo -u "${POSTGRES_USER};" psql c "CREATE DATABASE IF NOT EXISTS ${POSTGRES_DATABASE_NAME}"
# psql -v ON_ERROR_STOP=1 -c "CREATE USER ${POSTGRES_USER};CREATE DATABASE ${POSTGRES_DATABASE_NAME};"


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${POSTGRES_DATABASE_NAME}" <<-EOSQL
EOSQL