FROM node:16.15.0-alpine3.14

# Create app directory, this is in our container/in our image
WORKDIR /server/users-service
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
ADD /server/users-service/package.json ./package.json
ADD /server/users-service/nest-cli.json ./nest-cli.json
ADD /server/users-service/tsconfig.build.json ./tsconfig.build.json
ADD /server/users-service/tsconfig.json ./tsconfig.json


RUN npm install
# If you are building your code for production
# RUN npm ci --only=production
# COPY . .

CMD npm run start:dev
